Squashed 'clash-vexriscv/' changes from 2eced423..4806c8b6
4806c8b6 Merge pull request #66 from clash-lang/bump-ghcs
afd70d02 Simplify `cabal.project` by merging subdirs
a96cda05 Add support for GHC 9.8 and 9.10, drop support for 9.0 and 9.4
638080b9 Merge pull request #56 from clash-lang/in-reset-behavior-tests
67835969 Rename `Args` to `TestContext`
e5ece962 Add `--jtag-debug` on CI
f33b1325 Add reset assertion test
f27a1d78 Prettier JTAG debug output
4ae7e294 Add option to print CPU cycles
83d18eca Add option to assert reset in middle of execution
303fab59 Change flag names to be more descriptive
7428e9ca Prefix names in RunOpts to prevent future clashes
45ee942d Check whether we can recover from reset deassertion
b75a3cc6 Make number of reset cycles configurable
fc0f27a7 Test CPU chain access with one CPU in reset
04c2931a Fix stack traces for local expect functions
fb4dbc1e Fix comments in GDB scripts
246f25e8 Make debug output of expect function more readable/useful
da3b01a2 Set cache path to Cabal store set in `shell.nix` (#65)
3f9758a1 Check whether Nix shell works on CI (#61)
9363f8d4 Merge pull request #63 from clash-lang/improve-expect-functions
79c5e34a Add timeout to expect functions
ed39928d Add call stack to `waitForLine`
f1d76ead Use `tail` instead of `streaming` to follow files (#64)
e86580bf Remove enable from `cpu` (#58)
c69899c2 Drop register on wishbone bus (#59)
1715fc73 Print `JTAG bridge ready` and wait for it to prevent race conditions (#57)
1ca5a69d Merge pull request #53 from clash-lang/add-fourmolu
5e11a6f6 Add `.git-blame-ignore-revs`
2bd141e6 Add fourmolu formatting
96ad7244 Use `HasCallStack` instead of manual source line tracking (#52)
3900cb07 Bump OpenOCD (#54)
3a26b8bd Correcetly simulate passed time before first clock edge in verilator (#50)
51239127 Add post fetch step that removes `.git` (#48)
ca418fcb Merge pull request #47 from clash-lang/lucas/move-stoptime-ndmreset
27c82690 Move `ndmreset` and `stoptime` from `JtagOut` to `CpuOut`
68886c88 Merge pull request #46 from clash-lang/run-clang-format
a32dbc98 Add `clang-format-check` to ci
68ca4d0e Format with `clang-format`
9a676aa6 Add `clang` to nix shell
0d4be0e0 Merge pull request #45 from clash-lang/lucas/bump-jtag-interface
61c7719d Bump GHC versions on Docker images and rebuild
5f9a53c9 Add `.scala-build` to `.gitignore`
2c1ec3a3 Remove `openocd-vexriscv` from `nix` and `docker`
deabc085 Switch to `openocd-vexriscv` and use `remote-bitbang`
d987e396 Replace `DebugPlugin` with `EmbeddedRiscvJtag`
59298429 Add `nix` derivation for `openocv-riscv`
2dfda13f Add `.metals` to `.gitignore`
554f4af1 Bump scala and spinal version
720e5d44 Add execute permissions to `update-vexriscv.pu`
ad6edb75 Merge pull request #44 from clash-lang/lucas/add-docker-readme
636ac968 Extend readme with CI info
ac10433d Bump GHA actions (#43)
59215117 Merge pull request #42 from clash-lang/add-all-check
e697bfdd Fix typo: ouput -> output
e7e8e29c Add all check to CI

git-subtree-dir: clash-vexriscv
git-subtree-split: 4806c8b6b0c2fbe478f93d0e2d71eae38d7a261c

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,52 @@ on: [push]
 # That file determines which version gets used locally on developer machines.
 
 jobs:
+  nix-shell:
+    name: VexRiscv integration (Nix shell)
+    needs: [rust-build-programs]
+    runs-on: ubuntu-22.04
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install Nix
+        uses: cachix/install-nix-action@v30
+        with:
+          nix_path: nixpkgs=channel:nixos-unstable
+
+      - name: Enter Nix shell
+        run: |
+          nix-shell --run "echo 'Nix shell entered'"
+
+      - name: Update Cabal index info
+        run: |
+          cp .github/cabal.project cabal.project.local
+          nix-shell --run "cabal update"
+          nix-shell --run "cabal freeze"
+
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cabal-nix/store
+          key: packages-cachebust-4-nix-${{ hashFiles('cabal.project.freeze', 'cabal.project', 'shell.nix', 'nix/**/*.nix', 'nix/**/*.json') }}
+          restore-keys: packages-cachebust-4-nix
+
+      - name: Download VexRiscv Integration Tests
+        uses: actions/download-artifact@v4
+        with:
+          name: vexriscv-test-binaries
+
+      - name: Extract VexRiscv Integration Tests
+        run: |
+          tar -x -f vexriscv-test-binaries.tar
+
+      - run: nix-shell --run "cabal build all"
+      - run: nix-shell --run "cabal run clash-vexriscv:unittests"
+      - run: nix-shell --run "cabal run clash-vexriscv-sim:unittests -- -j1 --jtag-debug"
+      - run: nix-shell --run "cabal run clash-vexriscv-sim:hdl-test"
+
   license-check:
     runs-on: ubuntu-22.04
     container:
@@ -20,8 +66,43 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: REUSE Compliance Check
-      uses: fsfe/reuse-action@v2
+      uses: fsfe/reuse-action@v4
 
+  haskell-checks:
+    name: Haskell checks
+    runs-on: ubuntu-24.04
+    container:
+      image: ubuntu:24.04
+
+    steps:
+      - name: Install wget, git, python3
+        run: |
+          apt-get update
+          apt-get install python3 wget git -y
+
+      - name: Workaround GHA permission issues
+        run: |
+          git config --global --add safe.directory '*'
+
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Install fourmolu
+        run: |
+          version="0.14.1.0"
+          wget -O fourmolu "https://github.com/fourmolu/fourmolu/releases/download/v${version}/fourmolu-${version}-linux-x86_64"
+          chmod +x fourmolu
+          mv fourmolu /usr/bin/fourmolu
+
+      - name: Run formatting..
+        run: |
+          git status
+          .github/scripts/fourmolu.sh
+          .github/scripts/fix_spdx_header.py
+
+      - name: Check for differences
+        run: |
+          git diff --exit-code
 
   rust-checks:
     name: Rust checks
@@ -96,11 +177,23 @@ jobs:
           cd clash-vexriscv-sim; sh bundle_test_binaries.sh
 
       - name: Upload Integration Test Binaries
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: vexriscv-test-binaries
           path: clash-vexriscv-sim/vexriscv-test-binaries.tar
 
+  c-checks:
+    name: C checks
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: clang-format check
+        uses: jidicula/clang-format-action@v4.14.0
+        with:
+          clang-format-version: 16
+          check-path: '.'
 
   vex-riscv:
     name: VexRiscv integration
@@ -111,13 +204,12 @@ jobs:
       fail-fast: false
       matrix:
         ghc:
-          - "9.0.2"
-          - "9.2.8"
-          - "9.4.8"
           - "9.6.6"
+          - "9.8.4"
+          - "9.10.1"
 
     container:
-      image: ghcr.io/clash-lang/clash-vexriscv-ci:${{ matrix.ghc }}-20240823
+      image: ghcr.io/clash-lang/clash-vexriscv-ci:${{ matrix.ghc }}-20250211
 
     steps:
       - name: Checkout
@@ -129,12 +221,12 @@ jobs:
           cabal update
           cabal freeze
       - name: Cache
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: |
             ~/.local/state/cabal/store/
-          key: packages-cachebust-3-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze', 'cabal.project') }}
-          restore-keys: packages-cachebust-3-${{ matrix.ghc }}
+          key: packages-cachebust-4-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze', 'cabal.project') }}
+          restore-keys: packages-cachebust-4-${{ matrix.ghc }}
 
       - name: Stash existing VexRiscv.v
         run: |
@@ -151,7 +243,7 @@ jobs:
           cabal build clash-vexriscv-sim
 
       - name: Download VexRiscv Integration Tests
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: vexriscv-test-binaries
 
@@ -165,7 +257,7 @@ jobs:
 
       - name: OpenOCD bin symlink
         run: |
-          ln -s /opt/bin/openocd /opt/bin/openocd-vexriscv
+          ln -s /opt/bin/openocd /opt/bin/openocd-riscv
 
       - name: Run `clash-vexriscv` unittests
         run: |
@@ -174,8 +266,42 @@ jobs:
       - name: Run `clash-vexriscv-sim` unittests
         run: |
           # Can't run the unit tests with multiple threads because of the common use of port 7894.
-          cabal run clash-vexriscv-sim:unittests -- -j1
+          cabal run clash-vexriscv-sim:unittests -- -j1 --jtag-debug
 
       - name: Run `clash-vexriscv-sim` HDL test
         run: |
           cabal run clash-vexriscv-sim:hdl-test
+
+  all:
+    name: All jobs finished
+    if: ${{ !cancelled() }}
+    needs: [
+        'license-check',
+        'rust-checks',
+        'vex-riscv',
+        'rust-build-programs',
+        'nix-shell'
+      ]
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Check dependencies for failures
+        run: |
+          # Test all dependencies for success/failure
+          set -x
+          success="${{ contains(needs.*.result, 'success') }}"
+          fail="${{ contains(needs.*.result, 'failure') }}"
+          set +x
+
+          # Test whether success/fail variables contain sane values
+          if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
+          if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi
+
+          # We want to fail if one or more dependencies fail. For safety, we introduce
+          # a second check: if no dependencies succeeded something weird is going on.
+          if [[ "${fail}" == "true" || "${success}" == "false" ]]; then
+            echo "One or more dependency failed, or no dependency succeeded."
+            exit 1
+          fi
