Add selective synth and test CI runs for debugging
While debugging, we often only want one bittide instance to be tested with our
hardware-in-the-loop infrastructure. With the increasing number of bittide
instances with are synthesized and tested, these CI runs take a long time. With
this commit you can add a file `.github/synthesis/debug.json`, with only the
instances you want CI to synthesize/test. The CI run will always fail on the
'all' job when this file exists to prevent a premature merge.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -675,6 +675,8 @@ jobs:
         run: |
           if [[ "${{ github.event_name }}" == "schedule" || $(.github/scripts/force_expensive_checks.sh) == "true" ]]; then
             cp .github/synthesis/all.json checks.json
+          elif [[ -f .github/synthesis/debug.json ]]; then
+            cp .github/synthesis/debug.json checks.json
           else
             cp .github/synthesis/staging.json checks.json
           fi
@@ -705,6 +707,8 @@ jobs:
         run: |
           if [[ "${{ github.event_name }}" == "schedule" || $(.github/scripts/force_expensive_checks.sh) == "true" ]]; then
             cp .github/synthesis/all.json checks.json
+          elif [[ -f .github/synthesis/debug.json ]]; then
+            cp .github/synthesis/debug.json checks.json
           else
             cp .github/synthesis/staging.json checks.json
           fi
@@ -922,6 +926,12 @@ jobs:
           # Test whether success/fail variables contain sane values
           if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
           if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi
+
+          # If this is a debug run, fail even when all dependencies succeeded.
+          if [[ -f .github/synthesis/debug.json ]]; then
+            echo "This is a debug run, which may never succeed. Remove '.github/synthesis/debug.json' before trying to merge."
+            exit 1
+          fi
 
           # We want to fail if one or more dependencies fail. For safety, we introduce
           # a second check: if no dependencies succeeded something weird is going on.
